language: minimal

jobs:
  include:
    - stage: "trigger cs2fs-online pipeline"
      script: 
        - "curl -X POST -F token=$TOKEN -F ref=master https://gitlab.com/api/v4/projects/11538057/trigger/pipeline"
      if: branch = master
